theme: minima
title: Anthony’s Mac Labs Blog
url: https://maclabs.jazzace.ca
description: Anthony Reimer’s blog for Mac Admins that shares what he’s learned recently
author:
  name: Anthony Reimer
  mastodon: AnthonyReimer@mastodon.social
